### ISSUE TITLE
lair panicing while using LairServerInProc

### ISSUE THREAD

**Issue by Connoropolous** [holochain/lair#103]
for holochain-runner it would be super simplifying to switch to LairServerInProc since the idea is to have a really nice and simple one-stop-shop binary for executing a holochain happ. 

the branch I'm working on is here: https://github.com/lightningrodlabs/holochain-runner/pull/14

use of the config object: https://github.com/lightningrodlabs/holochain-runner/pull/14/files#diff-cba64c21ab992eaad29fce147a08f4560a4769bc14682b8a96081a5fd02dbecdR38-R40

ran into this error trying to put the LairServerInProc into use:
```
name = 'holochain-runner'
operating_system = 'unix:OSX'
crate_version = '0.2.0'
explanation = '''
Panic occurred in file '/Users/connor/.cargo/registry/src/github.com-1ecc6299db9ec823/lair_keystore_api-0.2.1/src/config.rs' at line 296
'''
cause = 'can decode as file path: ()'
method = 'Panic'
backtrace = '''

   0: 0x1060a0a3c - core::panicking::panic_fmt::h9fec86f6a9c4146e
                at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/panicking.rs:142
   1: 0x1060a0ae0 - core::result::unwrap_failed::h04f08301b97a771c
                at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/result.rs:1805
   2: 0x10597e5a0 - lair_keystore_api::config::get_connection_path::h16c3cafe1c73a9ed
   3: 0x104566340 - holochain_keystore::lair_keystore::spawn_lair_keystore_in_proc::{{closure}}::h4f2655f044d6229f
   4: 0x1045bc310 - holochain::conductor::conductor::builder::ConductorBuilder::build::{{closure}}::h48b1a8b39f1be7bb
   5: 0x1045b7794 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::ha8dbe1e39dacda40
   6: 0x10463ebd8 - std::thread::local::LocalKey<T>::with::h7e567c7d2cb1c726
   7: 0x1045516b8 - tokio::park::thread::CachedParkThread::block_on::h2b9b57a67050cce5
   8: 0x1045a1d08 - tokio::runtime::handle::Handle::block_on::h8bf57a092dfb8e16
   9: 0x1045f7a5c - tokio::runtime::scheduler::multi_thread::worker::block_in_place::h9ca055e07a6ff949
  10: 0x1045158c0 - holochain_runner::main::hf60f7f1227a0257e
  11: 0x104527bfc - std::sys_common::backtrace::__rust_begin_short_backtrace::hd1e9ad9d3bfe0d80
  12: 0x104680a8c - std::rt::lang_start::{{closure}}::h88b1cee7cf43e53e
  13: 0x105fe0160 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h6091bdce585e0c9c
                at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/ops/function.rs:280
                 - std::panicking::try::do_call::h2dde559bd47c537c
                at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:492
                 - std::panicking::try::h0be0a0414f498150
                at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:456
                 - std::panic::catch_unwind::h0dbebda9c8fcb6e3
                at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panic.rs:137
                 - std::rt::lang_start_internal::{{closure}}::h70683b79d9154b98
                at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/rt.rs:128
                 - std::panicking::try::do_call::h60888734191539e8
                at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:492
                 - std::panicking::try::h212200e2cf152f8d
                at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:456
                 - std::panic::catch_unwind::hf4ae91ebdc2dedaf
                at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panic.rs:137
                 - std::rt::lang_start_internal::h92a00ef694077615
                at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/rt.rs:128
  14: 0x104516284 - _main'''
```

@neonphog is there something special to know about using LairServerInProc or is this untested territory that I'm in?

**Comment by neonphog** [comment]
@Connoropolous - Can you send me the conductor config you are using?

I mainly need to know if your are setting the lair_root in the keystore config to something other than None...

Then, if it is None, did it create a `lair-keystore-config.yaml` file in your conductor environment `/keystore` directory? Or if you specified a path, did it create it in that path?

If it did, can you paste that too?

Thanks!

P.S. to answer your question, we have tests that show LairServerInProc working, so I'm thinking there's a file path bug, possibly one that is specific to macOs.

**Comment by Connoropolous** [comment]
thanks @neonphog I ran it with a Some value that was a real string to a real path, and I did see the file created in the path I specified

Here are some other diagnostics then... 

lair-keystore-config.yaml
```
connectionUrl: unix://test/data/keystore/socket?k=AO_lQTS9NDFdjT_FkIdHDbbHWM55aXAP8pnqSmOohzY

# The pid file for managing a running lair-keystore process
pidFile: test/data/keystore/pid_file

# The sqlcipher store file for persisting secrets
storeFile: test/data/keystore/store_file

# Configuration for managing sign_by_pub_key fallback
# in case the pub key does not exist in the lair store.
# - `signatureFallback: none`
# - ```
#   signatureFallback:
#     command:
#       # 'program' will resolve to a path, specifying 'echo'
#       # will try to run './echo', probably not what you want.
#       program: "./my-executable"
#       # args are optional
#       args:
#         - test-arg1
#         - test-arg2
#   ```
signatureFallback: none

# -- cryptographic secrets --
# If you modify the data below, you risk loosing access to your keys.
runtimeSecretsSalt: r25qUksWTIwn-c5_l15kbQ
runtimeSecretsMemLimit: 268435456
runtimeSecretsOpsLimit: 3
runtimeSecretsContextKey:
- XRf0d7Gs8WnSbg9LI4KLZZgtAblmnju1
- NRvH1Al1ySPOgmVPKwmy2BEhWkmFZxvJ0qBmyH9zbfOD4vBYqJGsdJ2MQnYxeUkeOw
runtimeSecretsIdSeed:
- UAcZLdGS932YMxEGl8Kb_tY4Wvb2Pkjh
- zcdBh8n0eYU8lACsDG_nKpA3q7V6mXxzdkg-_IdECouYgyAp-BaoE4t-KezZyXNaDg
```

![signal-2022-09-26-111540_002](https://user-images.githubusercontent.com/1409121/192351079-839300e0-0b10-4e8c-96b9-6aa26af18367.png)
![signal-2022-09-26-111505_002](https://user-images.githubusercontent.com/1409121/192351084-202d8936-3c4d-4fb8-9600-d96c53b86271.png)


Oh! I just noticed the oddity in my screenshot, which is the duplication!

**Comment by Connoropolous** [comment]
oops, correction! ignore what I mentioned about duplication, I must have run it once without providing my own custom one, and then it picked the default, and I didn't delete it. 

After deleting both, and rerunning, the keystore-config file appears in my intended directory, but the error persists

**Comment by neonphog** [comment]
@Connoropolous - Thanks! I think I see the problem. I've only tested with absolute paths, and it looks like yours are relative. Would you mind trying an absolute one to see if that works?

If it does, the simplest solution in my mind would be to convert it to absolute when taking the path from the conductor config and writing the lair config. Do you see any problem with that?

**Comment by Connoropolous** [comment]
ah gotcha. Yes that would make sense. I'll check and report back

**Comment by Connoropolous** [comment]
Yeah @neonphog I can confirm it then worked with an absolute path

**Comment by Connoropolous** [comment]
<img width="1190" alt="Screen Shot 2022-09-26 at 3 01 13 PM" src="https://user-images.githubusercontent.com/1409121/192388521-054484e8-adcf-4d2a-9f0a-057649cfd2f7.png">

**Comment by Connoropolous** [comment]
I've been able to go ahead with my things knowing this constraint. Can leave this open or close it as you deem relevant. Might be useful if youre going to leave it as is to change the panic description to help devs identify the root cause

**Comment by neonphog** [comment]
Thanks @Connoropolous - yeah, I'll leave it open, though the fix will actually come in the holochain repo to make an absolute path when generating the lair config.
