### ISSUE TITLE
sqlcipher dependency, for shipping happs, or just compiling

### ISSUE THREAD

**Issue by Connoropolous** [holochain/lair#43]
@neonphog 
I posted in one of the chat spaces, but I don't think you're there, sorry it's so colloquial, but for time saving purposes I'm just going to paste it in:

oh dannnggg. just realized a painful truth, unless I'm so mistaken. 
sqlcipher is a true external dependency, and can't be bundled into the MacOs lair-keystore dependency :frowning: :frowning: :frowning: 
Without it, you confusingly get: 
"Connection Refused"
back from the lair-keystore socket, and then goes and starts trying to run cargo install lair_keystore on the system.
For acorn, where we bundle everything, this is a deal breaking sad change, because it means having to push people back around to the command line which we have taken enormous efforts to avoid

There are a few projects, Launcher, Snapmail, and Acorn at the front of my mind, that this will affect because the intention is to provide a full package to end users. 

Cc @ddd-mtl @guillemcordoba

___
Update: 

As a static linked library
David Braden discovered an environment variable that may be key to making this work:
SQLCIPHER_STATIC=1
https://github.com/holochain/lair/issues/43#issuecomment-907376852
set this environment variable before compiling lair-keystore

For installation: 
Linux: `sudo apt-get install libsqlcipher-dev`
Mac: `brew install sqlcipher`

**Comment by Connoropolous** [comment]
@neonphog still haven't tried this, but if this works, something about this dependency on sqlcipher could usefully go in the readme to clarify these things, what to do for dynamic linking (which libs) and how to handle static linking

**Comment by neonphog** [comment]
hopefully this'll all go away with 966 and `bundled-sqlcipher`, but yea, feel free to add something to the readme.

realistically this should be a hard dependency on holochain too, but we're also allowing the insecure fallback to sqlite there.

**Comment by Connoropolous** [comment]
so with Sprillow we have clients paying us and counting on us to ship applications NOW built on Holochain, so anything 'hopefully' isn't the way that we depend on Holochain :)

The lack of communication about the introduction of sqlcipher as a dependency has already led to numerous lost hours, and appears to continue to for others https://github.com/holochain/holochain/issues/953. This user got the error when running `holochain -i` because it tried to do the on-demand download and install of lair-keystore and does not fail remotely gracefully.

**Comment by neonphog** [comment]
@Connoropolous - the sqlcipher dependency addition is mentioned in the [holochain CHANGELOG.md](https://github.com/holochain/holochain/blob/develop/CHANGELOG.md) - although I get how the impact is not super clear given Windows still uses sqlite so it mentions that and doesn't make it clear that is not an option on Linux / macOs.

It would be irresponsible to release a key manager that leaves the keys unencrypted on disk. Holochain is an alpha product, and we really are 'hopefully' awaiting upstream fixes like 966 that will make this experience better to work with, not to mention secure at all on the Windows platform.

I apologize that in this case our efforts to point out these new requirements fell short. We will continue to make the effort in the future.

**Comment by Connoropolous** [comment]
Thanks @neonphog 

It's good that something sqlcipher gets mentioned in the changelog, it could have been made clear and actionable just with 'sqlcipher is a new system dependency, it will need to be installed on your system' and bonus 'here's a pointer how or where to look'. The way it's written lends no insight into what it is or its implications, for all those of us who will have never even heard of sqlcipher before, which I'm guessing is most people. 

Again, appreciate your response, and if I get a chance I'll contribute a PR that adds a word of caution

**Comment by artbrock** [comment]
@Connoropolous You know we've had [a job listing](https://holo.host/careers/app-test-developer/) for quite a while now looking to hire someone to help us catch and document these things better upon release. You know... playing a role somewhat similar to what you did for the Holochain team for a while.

It is certainly a known gap that we're trying to address. So far we've been focused on getting the release process automated with basic changelog documentation, but there are definitely still gaps in that process. Thanks for pointing the need on the sqlcipher issue. We hope to get these things smoother soon.

**Comment by Connoropolous** [comment]
Itd be superb to see it filled! I hope it does. 

We'll continue to do what we can when we can from our angle. Sprillow is growing a bit, team wise, and the scope of the projects. Will update you sometime soon

**Comment by neonphog** [comment]
hopefully this is resolved for now on linux and macOs with the new bundled-sqlcipher-vendored-openssl feature being used (and windows still doesn't have at-rest encryption : (...  ) Feel free to re-open if there are still issues.
