### ISSUE TITLE
help, what dependency is missing when it says-> note: ld: library not found for -lcrypto

### ISSUE THREAD

**Issue by Connoropolous** [holochain/lair#56]
OS: mac

Running: cargo install lair_keystore --root . --version 0.0.3

error: linking with `cc` failed: exit status: 1
 note: ld: library not found for -lcrypto

see the CI run here: https://github.com/Sprillow/holochain-runner/runs/3660025657?check_suite_focus=true

@neonphog any advice you can give? 
Also note: I am setting SQLCIPHER_STATIC=1

**Comment by Connoropolous** [comment]
update, I have tried running 
`brew install openssl` as well as `brew install libsodium` prior to this command, but both report they are already installed on the system

**Comment by neonphog** [comment]
@Connoropolous 

Can you try `brew link openssl` and if it gives you an error try one of the suggestions per [this comment](https://gist.github.com/aklap/e885721ef15c8668ed0a1dd64d2ea1a7#gistcomment-2814899)?

**Comment by Connoropolous** [comment]
Ok thanks @neonphog I will try

**Comment by jdeepee** [comment]
We are also running into this issue for our mac builds happening inside github actions. You can see the CI run here: https://github.com/juntofoundation/communities/runs/3735439921?check_suite_focus=true

Have tried exporting paths looking like: `/usr/local/opt/openssl/` & also as suggested looking like: `/usr/local/opt/openssl@1.1/`.

**Comment by jdeepee** [comment]
(that CI run is trying to build the latest commit on this repo)

**Comment by neonphog** [comment]
@Connoropolous @jdeepee - there's a pending [vendored-openssl feature](https://github.com/rusqlite/rusqlite/blob/master/Cargo.toml#L38) coming down the pipeline that will help with this once it's released.

[maybe soon??](https://github.com/rusqlite/rusqlite/issues/1019)

Unfortunately, I don't have a mac to test with. It might be possible to patch the rusqlite dependency to github to test it out ahead of time.

**Comment by Connoropolous** [comment]
Yeah actually, that is what @guillemcordoba ended up doing I think for Launcher... I will get the reference

**Comment by Connoropolous** [comment]
@jdeepee and @neonphog 
here is @guillemcordoba fork: https://github.com/guillemcordoba/lair/commit/54e8168a15bc9b1a5f8a8222e97e66fa85794883 
you can point to it @jdeepee 
I would ask @guillemcordoba (or know where to look) to find out what exact version it is though and make sure that suits your needs

**Comment by guillemcordoba** [comment]
What I basically did is to disable the encryption at rest... It's in the bundled-sqlite branch.

**Comment by jdeepee** [comment]
Thanks for that @guillemcordoba enabled me to ship an internal build for our team :)

**Comment by neonphog** [comment]
[rusqlite 0.26.0 released](https://crates.io/crates/rusqlite/0.26.0) i'll do some testing and hopefully bump both lair and holochain deps

**Comment by neonphog** [comment]
Looking good.
- I was able to [remove the CI commands that install sqlcipher in lair](https://github.com/holochain/lair/pull/74) ... working on Ubuntu and macOs.
- [Holochain PR updating to this lair / rusqlite](https://github.com/holochain/holochain/pull/1023)

**Comment by Connoropolous** [comment]
Awesome
